// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyiqufzgdezmvjcutysu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aXF1ZnpnZGV6bXZqY3V0eXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTUzMTQsImV4cCI6MjA2MjI5MTMxNH0.m2vlqP4-VIXTDZphurr8BMwa8_3-Q6-or3Sljlenalw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);